name: Testing
on:
  push:
    branches: [ying-testing]
jobs:
  TestingMacos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm test topiQLFolder.test.js
