name: Testing
on:
  push:
    branches: [ying-testing]
jobs:
  TestingMacos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: jest topiQLFolder.test.js
