name: testing

on:
  push:
    branches: [ ci-testing ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-11

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
